// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apitienda.Data;

#nullable disable

namespace apitienda.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250517050309_AddTokenBlacklistTable")]
    partial class AddTokenBlacklistTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PasswordResetToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.ToTable("passwordresettoken");
                });

            modelBuilder.Entity("apitienda.Models.TokenBlacklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokenBlacklist");
                });

            modelBuilder.Entity("apitienda.Models.Usuario", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("address_city")
                        .HasColumnType("text");

                    b.Property<string>("address_complement")
                        .HasColumnType("text");

                    b.Property<string>("address_interior_number")
                        .HasColumnType("text");

                    b.Property<string>("address_neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("address_number")
                        .HasColumnType("text");

                    b.Property<string>("address_state")
                        .HasColumnType("text");

                    b.Property<string>("address_zip_code")
                        .HasColumnType("text");

                    b.Property<string>("contact_phone_number")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("date_joined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("email_verified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("email_verified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_superuser")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("last_login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("modified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nationality")
                        .HasColumnType("text");

                    b.Property<string>("occupation")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password_reset_token")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("password_reset_token_expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("profile_picture")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("apitienda.Models.TokenBlacklist", b =>
                {
                    b.HasOne("apitienda.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
